// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Diploma.DB;

namespace Diploma.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221012155700_AddedOrderTables")]
    partial class AddedOrderTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Module6HW7.Models.Catalog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImgUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RouteName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CatalogItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImgUrl = "https://content1.rozetka.com.ua/goods/images/big_tile/267792323.jpg",
                            RouteName = "teapots",
                            Title = "Teapots"
                        },
                        new
                        {
                            Id = 2,
                            ImgUrl = "https://content.rozetka.com.ua/goods/images/big_tile/160433459.jpg",
                            RouteName = "coffee-machines",
                            Title = "Coffee machines"
                        });
                });

            modelBuilder.Entity("Module6HW7.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderStatusId")
                        .HasColumnType("int");

                    b.Property<string>("Patronymic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TotalSum")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("OrderStatusId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Module6HW7.Models.OrderProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderProducts");
                });

            modelBuilder.Entity("Module6HW7.Models.OrderStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OrderStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Awaiting confirmation"
                        },
                        new
                        {
                            Id = 2,
                            Title = "Accepted"
                        },
                        new
                        {
                            Id = 3,
                            Title = "Packing"
                        },
                        new
                        {
                            Id = 4,
                            Title = "In delivery"
                        },
                        new
                        {
                            Id = 5,
                            Title = "Deliveried"
                        },
                        new
                        {
                            Id = 6,
                            Title = "Declined"
                        });
                });

            modelBuilder.Entity("Module6HW7.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Capacity")
                        .HasColumnType("float");

                    b.Property<int>("CatalogId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManufacturerCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WarrantyInMonths")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CatalogId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2462b05b-bd0b-4a59-aa8c-43db07c37b06"),
                            Capacity = 1.7,
                            CatalogId = 1,
                            Description = "Safety in 3 dimensions: automatic shutdown, protection against leakage and overheating, LED indication.",
                            ImgUrl = "https://content.rozetka.com.ua/goods/images/big_tile/10648417.jpg",
                            ManufacturerCountry = "China",
                            Price = 1199.0,
                            Quantity = 8,
                            Title = "Teapot BOSCH TWK3A013",
                            WarrantyInMonths = 12
                        },
                        new
                        {
                            Id = new Guid("252caea1-dbf5-40bf-b348-13680d582f16"),
                            Capacity = 1.7,
                            CatalogId = 1,
                            Description = "Inspired by traditional British ceramics, the Loft teapot's stunning fluted lines are elegantly paired with modern chrome accents for a timeless design that looks great in any kitchen.",
                            ImgUrl = "https://content1.rozetka.com.ua/goods/images/big_tile/64732971.jpg",
                            ManufacturerCountry = "China",
                            Price = 1299.0,
                            Quantity = 12,
                            Title = "Teapot TEFAL LOFT KO250830",
                            WarrantyInMonths = 24
                        },
                        new
                        {
                            Id = new Guid("da04b0c4-4b2d-41ea-bb81-99c81c1b24bb"),
                            Capacity = 1.7,
                            CatalogId = 1,
                            Description = "Safety in 3 dimensions: automatic shutdown, protection against leakage and overheating, LED indication.",
                            ImgUrl = "https://content1.rozetka.com.ua/goods/images/big_tile/19966325.jpg",
                            ManufacturerCountry = "China",
                            Price = 2299.0,
                            Quantity = 7,
                            Title = "Teapot BOSCH TWK3P423",
                            WarrantyInMonths = 24
                        },
                        new
                        {
                            Id = new Guid("a66cc908-1648-4855-ab96-843528fc7c03"),
                            Capacity = 1.7,
                            CatalogId = 1,
                            Description = "Prepare hot drinks in no time with 2200W of power",
                            ImgUrl = "https://content1.rozetka.com.ua/goods/images/big_tile/267792323.jpg",
                            ManufacturerCountry = "China",
                            Price = 2349.0,
                            Quantity = 13,
                            Title = "Teapot Philips Eco HD9365/10",
                            WarrantyInMonths = 24
                        },
                        new
                        {
                            Id = new Guid("fdecad03-4d1b-40a4-b4d9-7333d40162db"),
                            Capacity = 1.7,
                            CatalogId = 1,
                            Description = "With keep warm function; fast, safe boiling; easy to fill, use and clean",
                            ImgUrl = "https://content2.rozetka.com.ua/goods/images/big_tile/274310222.jpg",
                            ManufacturerCountry = "China",
                            Price = 2399.0,
                            Quantity = 7,
                            Title = "Teapot Philips Viva Collection HD9355/92",
                            WarrantyInMonths = 24
                        },
                        new
                        {
                            Id = new Guid("4988c0b0-aafe-4cf3-af01-15305bdb886e"),
                            Capacity = 1.5,
                            CatalogId = 1,
                            Description = "With the AENO EK4 electric kettle, you can boil water in just 5 minutes and have time to prepare tea or coffee for the arrival of guests.",
                            ImgUrl = "https://content2.rozetka.com.ua/goods/images/big_tile/248635439.jpg",
                            ManufacturerCountry = "China",
                            Price = 1099.0,
                            Quantity = 9,
                            Title = "Teapot AENO EK4",
                            WarrantyInMonths = 24
                        },
                        new
                        {
                            Id = new Guid("43b49ab8-7eb4-4450-9f41-106049f26e61"),
                            Capacity = 1.5,
                            CatalogId = 1,
                            Description = "Good teapot",
                            ImgUrl = "https://content.rozetka.com.ua/goods/images/big_tile/14708920.jpg",
                            ManufacturerCountry = "China",
                            Price = 1399.0,
                            Quantity = 9,
                            Title = "Teapot 7",
                            WarrantyInMonths = 12
                        },
                        new
                        {
                            Id = new Guid("3eafd7da-9300-4fb6-b710-d2e563d3c8c0"),
                            Capacity = 1.5,
                            CatalogId = 1,
                            Description = "Good teapot",
                            ImgUrl = "https://content1.rozetka.com.ua/goods/images/big_tile/283417981.png",
                            ManufacturerCountry = "China",
                            Price = 1469.0,
                            Quantity = 9,
                            Title = "Teapot 8",
                            WarrantyInMonths = 12
                        },
                        new
                        {
                            Id = new Guid("9b03eb5d-4847-4bec-964d-181ab1a31578"),
                            Capacity = 1.5,
                            CatalogId = 1,
                            Description = "Good teapot",
                            ImgUrl = "https://content1.rozetka.com.ua/goods/images/big_tile/10626237.jpg",
                            ManufacturerCountry = "China",
                            Price = 1599.0,
                            Quantity = 9,
                            Title = "Teapot 9",
                            WarrantyInMonths = 12
                        },
                        new
                        {
                            Id = new Guid("6d74e0cb-178c-4e6f-bdba-19cdb652827b"),
                            Capacity = 1.5,
                            CatalogId = 1,
                            Description = "Good teapot",
                            ImgUrl = "https://content1.rozetka.com.ua/goods/images/big_tile/81865256.jpg",
                            ManufacturerCountry = "China",
                            Price = 2399.0,
                            Quantity = 9,
                            Title = "Teapot 10",
                            WarrantyInMonths = 12
                        },
                        new
                        {
                            Id = new Guid("6b787234-3bcf-4471-8b32-feb706351b23"),
                            Capacity = 1.5,
                            CatalogId = 1,
                            Description = "Good teapot",
                            ImgUrl = "https://content.rozetka.com.ua/goods/images/big_tile/142971427.jpg",
                            ManufacturerCountry = "China",
                            Price = 2899.0,
                            Quantity = 9,
                            Title = "Teapot 11",
                            WarrantyInMonths = 12
                        },
                        new
                        {
                            Id = new Guid("4f76eaea-0c15-4aa3-942b-ec099cf5dbba"),
                            Capacity = 1.5,
                            CatalogId = 1,
                            Description = "Good teapot",
                            ImgUrl = "https://content.rozetka.com.ua/goods/images/big_tile/163131692.jpg",
                            ManufacturerCountry = "China",
                            Price = 2229.0,
                            Quantity = 9,
                            Title = "Teapot 12",
                            WarrantyInMonths = 12
                        },
                        new
                        {
                            Id = new Guid("5e56f88d-7dc1-4925-b470-0d1559aae954"),
                            Capacity = 12.0,
                            CatalogId = 2,
                            Description = "Good teapot",
                            ImgUrl = "https://content.rozetka.com.ua/goods/images/big_tile/160433459.jpg",
                            ManufacturerCountry = "China",
                            Price = 2229.0,
                            Quantity = 9,
                            Title = "Coffee machine 1",
                            WarrantyInMonths = 12
                        },
                        new
                        {
                            Id = new Guid("78a58103-2438-4fde-8678-80a36ee27ae0"),
                            Capacity = 12.0,
                            CatalogId = 2,
                            Description = "Good teapot",
                            ImgUrl = "https://content.rozetka.com.ua/goods/images/big_tile/15790055.jpg",
                            ManufacturerCountry = "China",
                            Price = 1579.0,
                            Quantity = 3,
                            Title = "Coffee machine 2",
                            WarrantyInMonths = 24
                        },
                        new
                        {
                            Id = new Guid("8d0be75b-6433-46c7-b9bd-ecc3205aece3"),
                            Capacity = 12.0,
                            CatalogId = 2,
                            Description = "Good teapot",
                            ImgUrl = "https://content2.rozetka.com.ua/goods/images/big_tile/29270053.jpg",
                            ManufacturerCountry = "China",
                            Price = 2379.0,
                            Quantity = 5,
                            Title = "Coffee machine 3",
                            WarrantyInMonths = 18
                        },
                        new
                        {
                            Id = new Guid("bcc857d0-7a5c-42c1-a0bd-3970655465e1"),
                            Capacity = 12.0,
                            CatalogId = 2,
                            Description = "Good teapot",
                            ImgUrl = "https://content2.rozetka.com.ua/goods/images/big_tile/160392353.jpg",
                            ManufacturerCountry = "China",
                            Price = 1899.0,
                            Quantity = 17,
                            Title = "Coffee machine 4",
                            WarrantyInMonths = 12
                        },
                        new
                        {
                            Id = new Guid("4b133f49-b447-4e61-af36-f8d6e05c4332"),
                            Capacity = 12.0,
                            CatalogId = 2,
                            Description = "Good teapot",
                            ImgUrl = "https://content.rozetka.com.ua/goods/images/big_tile/76717007.jpg",
                            ManufacturerCountry = "China",
                            Price = 1989.0,
                            Quantity = 3,
                            Title = "Coffee machine 5",
                            WarrantyInMonths = 6
                        },
                        new
                        {
                            Id = new Guid("776f9250-fe92-4597-b582-26c935089e67"),
                            Capacity = 12.0,
                            CatalogId = 2,
                            Description = "Good teapot",
                            ImgUrl = "https://content.rozetka.com.ua/goods/images/big_tile/45610581.jpg",
                            ManufacturerCountry = "China",
                            Price = 2359.0,
                            Quantity = 9,
                            Title = "Coffee machine 6",
                            WarrantyInMonths = 30
                        },
                        new
                        {
                            Id = new Guid("aea2d628-d00c-428d-bb76-9852d3239df0"),
                            Capacity = 12.0,
                            CatalogId = 2,
                            Description = "Good teapot",
                            ImgUrl = "https://content1.rozetka.com.ua/goods/images/big_tile/160843463.jpg",
                            ManufacturerCountry = "China",
                            Price = 3599.0,
                            Quantity = 10,
                            Title = "Coffee machine 7",
                            WarrantyInMonths = 24
                        },
                        new
                        {
                            Id = new Guid("120383ff-6862-4c5f-a1ac-def3743bc8b6"),
                            Capacity = 12.0,
                            CatalogId = 2,
                            Description = "Good teapot",
                            ImgUrl = "https://content.rozetka.com.ua/goods/images/big_tile/167686386.jpg",
                            ManufacturerCountry = "China",
                            Price = 4179.0,
                            Quantity = 8,
                            Title = "Coffee machine 8",
                            WarrantyInMonths = 6
                        },
                        new
                        {
                            Id = new Guid("29ef339a-7c47-4ffc-9a2b-6d666b3b9646"),
                            Capacity = 12.0,
                            CatalogId = 2,
                            Description = "Good teapot",
                            ImgUrl = "https://content.rozetka.com.ua/goods/images/big_tile/13821301.jpg",
                            ManufacturerCountry = "China",
                            Price = 1789.0,
                            Quantity = 5,
                            Title = "Coffee machine 9",
                            WarrantyInMonths = 24
                        },
                        new
                        {
                            Id = new Guid("47080ea7-dab0-4d76-bdd8-5a703f3bba15"),
                            Capacity = 12.0,
                            CatalogId = 2,
                            Description = "Good teapot",
                            ImgUrl = "https://content2.rozetka.com.ua/goods/images/big_tile/11675316.jpg",
                            ManufacturerCountry = "China",
                            Price = 6789.0,
                            Quantity = 7,
                            Title = "Coffee machine 10",
                            WarrantyInMonths = 12
                        });
                });

            modelBuilder.Entity("Module6HW7.Models.Order", b =>
                {
                    b.HasOne("Module6HW7.Models.OrderStatus", "OrderStatus")
                        .WithMany()
                        .HasForeignKey("OrderStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderStatus");
                });

            modelBuilder.Entity("Module6HW7.Models.OrderProduct", b =>
                {
                    b.HasOne("Module6HW7.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Module6HW7.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Module6HW7.Models.Product", b =>
                {
                    b.HasOne("Module6HW7.Models.Catalog", "Catalog")
                        .WithMany()
                        .HasForeignKey("CatalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Catalog");
                });
#pragma warning restore 612, 618
        }
    }
}
