// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Diploma.DB;

#nullable disable

namespace Diploma.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221015215500_AddedUserAndRoleEntities")]
    partial class AddedUserAndRoleEntities
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Module6HW7.Models.Catalog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ImgUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RouteName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CatalogItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImgUrl = "https://content1.rozetka.com.ua/goods/images/big_tile/267792323.jpg",
                            RouteName = "teapots",
                            Title = "Teapots"
                        },
                        new
                        {
                            Id = 2,
                            ImgUrl = "https://content.rozetka.com.ua/goods/images/big_tile/160433459.jpg",
                            RouteName = "coffee-machines",
                            Title = "Coffee machines"
                        });
                });

            modelBuilder.Entity("Module6HW7.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderStatusId")
                        .HasColumnType("int");

                    b.Property<string>("Patronymic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TotalSum")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("OrderStatusId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Module6HW7.Models.OrderProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderProducts");
                });

            modelBuilder.Entity("Module6HW7.Models.OrderStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OrderStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Awaiting confirmation"
                        },
                        new
                        {
                            Id = 2,
                            Title = "Accepted"
                        },
                        new
                        {
                            Id = 3,
                            Title = "Packing"
                        },
                        new
                        {
                            Id = 4,
                            Title = "In delivery"
                        },
                        new
                        {
                            Id = 5,
                            Title = "Deliveried"
                        },
                        new
                        {
                            Id = 6,
                            Title = "Declined"
                        });
                });

            modelBuilder.Entity("Module6HW7.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Capacity")
                        .HasColumnType("float");

                    b.Property<int>("CatalogId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManufacturerCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WarrantyInMonths")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CatalogId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3692e4c6-bd5c-4a68-b0c9-76119365a085"),
                            Capacity = 1.7,
                            CatalogId = 1,
                            Description = "Safety in 3 dimensions: automatic shutdown, protection against leakage and overheating, LED indication.",
                            ImgUrl = "https://content.rozetka.com.ua/goods/images/big_tile/10648417.jpg",
                            ManufacturerCountry = "China",
                            Price = 1199.0,
                            Quantity = 8,
                            Title = "Teapot BOSCH TWK3A013",
                            WarrantyInMonths = 12
                        },
                        new
                        {
                            Id = new Guid("276a5c4e-63af-445c-ad60-bb9f6cd88541"),
                            Capacity = 1.7,
                            CatalogId = 1,
                            Description = "Inspired by traditional British ceramics, the Loft teapot's stunning fluted lines are elegantly paired with modern chrome accents for a timeless design that looks great in any kitchen.",
                            ImgUrl = "https://content1.rozetka.com.ua/goods/images/big_tile/64732971.jpg",
                            ManufacturerCountry = "China",
                            Price = 1299.0,
                            Quantity = 12,
                            Title = "Teapot TEFAL LOFT KO250830",
                            WarrantyInMonths = 24
                        },
                        new
                        {
                            Id = new Guid("7190e884-e123-4378-882e-50ebe4fc1faf"),
                            Capacity = 1.7,
                            CatalogId = 1,
                            Description = "Safety in 3 dimensions: automatic shutdown, protection against leakage and overheating, LED indication.",
                            ImgUrl = "https://content1.rozetka.com.ua/goods/images/big_tile/19966325.jpg",
                            ManufacturerCountry = "China",
                            Price = 2299.0,
                            Quantity = 7,
                            Title = "Teapot BOSCH TWK3P423",
                            WarrantyInMonths = 24
                        },
                        new
                        {
                            Id = new Guid("a1f5fc9f-0590-4b7a-ad30-fa750e3d9a32"),
                            Capacity = 1.7,
                            CatalogId = 1,
                            Description = "Prepare hot drinks in no time with 2200W of power",
                            ImgUrl = "https://content1.rozetka.com.ua/goods/images/big_tile/267792323.jpg",
                            ManufacturerCountry = "China",
                            Price = 2349.0,
                            Quantity = 13,
                            Title = "Teapot Philips Eco HD9365/10",
                            WarrantyInMonths = 24
                        },
                        new
                        {
                            Id = new Guid("9f586e44-8e0c-47b2-b6d7-91747a9cecf0"),
                            Capacity = 1.7,
                            CatalogId = 1,
                            Description = "With keep warm function; fast, safe boiling; easy to fill, use and clean",
                            ImgUrl = "https://content2.rozetka.com.ua/goods/images/big_tile/274310222.jpg",
                            ManufacturerCountry = "China",
                            Price = 2399.0,
                            Quantity = 7,
                            Title = "Teapot Philips Viva Collection HD9355/92",
                            WarrantyInMonths = 24
                        },
                        new
                        {
                            Id = new Guid("f8666f85-7eb1-45cf-b0d8-427d97228b12"),
                            Capacity = 1.5,
                            CatalogId = 1,
                            Description = "With the AENO EK4 electric kettle, you can boil water in just 5 minutes and have time to prepare tea or coffee for the arrival of guests.",
                            ImgUrl = "https://content2.rozetka.com.ua/goods/images/big_tile/248635439.jpg",
                            ManufacturerCountry = "China",
                            Price = 1099.0,
                            Quantity = 9,
                            Title = "Teapot AENO EK4",
                            WarrantyInMonths = 24
                        },
                        new
                        {
                            Id = new Guid("9da50ad4-49d8-4599-8cef-effbd4f7c65a"),
                            Capacity = 1.5,
                            CatalogId = 1,
                            Description = "Good teapot",
                            ImgUrl = "https://content.rozetka.com.ua/goods/images/big_tile/14708920.jpg",
                            ManufacturerCountry = "China",
                            Price = 1399.0,
                            Quantity = 9,
                            Title = "Teapot 7",
                            WarrantyInMonths = 12
                        },
                        new
                        {
                            Id = new Guid("7ba0fcbd-910a-4a3a-b7f0-d5d2be8d100d"),
                            Capacity = 1.5,
                            CatalogId = 1,
                            Description = "Good teapot",
                            ImgUrl = "https://content1.rozetka.com.ua/goods/images/big_tile/283417981.png",
                            ManufacturerCountry = "China",
                            Price = 1469.0,
                            Quantity = 9,
                            Title = "Teapot 8",
                            WarrantyInMonths = 12
                        },
                        new
                        {
                            Id = new Guid("c5df9964-815f-4eb0-bc3c-7e0dfd27c279"),
                            Capacity = 1.5,
                            CatalogId = 1,
                            Description = "Good teapot",
                            ImgUrl = "https://content1.rozetka.com.ua/goods/images/big_tile/10626237.jpg",
                            ManufacturerCountry = "China",
                            Price = 1599.0,
                            Quantity = 9,
                            Title = "Teapot 9",
                            WarrantyInMonths = 12
                        },
                        new
                        {
                            Id = new Guid("20133e0e-0bb5-4290-822c-8dcf37ed6cd0"),
                            Capacity = 1.5,
                            CatalogId = 1,
                            Description = "Good teapot",
                            ImgUrl = "https://content1.rozetka.com.ua/goods/images/big_tile/81865256.jpg",
                            ManufacturerCountry = "China",
                            Price = 2399.0,
                            Quantity = 9,
                            Title = "Teapot 10",
                            WarrantyInMonths = 12
                        },
                        new
                        {
                            Id = new Guid("0796ed9e-cb7f-4130-a8b2-28d3c5f0c720"),
                            Capacity = 1.5,
                            CatalogId = 1,
                            Description = "Good teapot",
                            ImgUrl = "https://content.rozetka.com.ua/goods/images/big_tile/142971427.jpg",
                            ManufacturerCountry = "China",
                            Price = 2899.0,
                            Quantity = 9,
                            Title = "Teapot 11",
                            WarrantyInMonths = 12
                        },
                        new
                        {
                            Id = new Guid("75882fd4-020b-43e4-a075-32574bb15e14"),
                            Capacity = 1.5,
                            CatalogId = 1,
                            Description = "Good teapot",
                            ImgUrl = "https://content.rozetka.com.ua/goods/images/big_tile/163131692.jpg",
                            ManufacturerCountry = "China",
                            Price = 2229.0,
                            Quantity = 9,
                            Title = "Teapot 12",
                            WarrantyInMonths = 12
                        },
                        new
                        {
                            Id = new Guid("67c19187-8943-445a-92b7-54e0eadc9f59"),
                            Capacity = 12.0,
                            CatalogId = 2,
                            Description = "Good teapot",
                            ImgUrl = "https://content.rozetka.com.ua/goods/images/big_tile/160433459.jpg",
                            ManufacturerCountry = "China",
                            Price = 2229.0,
                            Quantity = 9,
                            Title = "Coffee machine 1",
                            WarrantyInMonths = 12
                        },
                        new
                        {
                            Id = new Guid("b8ce36bd-e3d2-4c3e-8d14-c61afad51617"),
                            Capacity = 12.0,
                            CatalogId = 2,
                            Description = "Good teapot",
                            ImgUrl = "https://content.rozetka.com.ua/goods/images/big_tile/15790055.jpg",
                            ManufacturerCountry = "China",
                            Price = 1579.0,
                            Quantity = 3,
                            Title = "Coffee machine 2",
                            WarrantyInMonths = 24
                        },
                        new
                        {
                            Id = new Guid("fe55b3ca-40c7-4e69-8727-e3be26f72e53"),
                            Capacity = 12.0,
                            CatalogId = 2,
                            Description = "Good teapot",
                            ImgUrl = "https://content2.rozetka.com.ua/goods/images/big_tile/29270053.jpg",
                            ManufacturerCountry = "China",
                            Price = 2379.0,
                            Quantity = 5,
                            Title = "Coffee machine 3",
                            WarrantyInMonths = 18
                        },
                        new
                        {
                            Id = new Guid("5ed562e4-b10e-4a11-ae61-05766a822ba1"),
                            Capacity = 12.0,
                            CatalogId = 2,
                            Description = "Good teapot",
                            ImgUrl = "https://content2.rozetka.com.ua/goods/images/big_tile/160392353.jpg",
                            ManufacturerCountry = "China",
                            Price = 1899.0,
                            Quantity = 17,
                            Title = "Coffee machine 4",
                            WarrantyInMonths = 12
                        },
                        new
                        {
                            Id = new Guid("07bf2ed0-eb26-480f-a8e6-7232efdad21e"),
                            Capacity = 12.0,
                            CatalogId = 2,
                            Description = "Good teapot",
                            ImgUrl = "https://content.rozetka.com.ua/goods/images/big_tile/76717007.jpg",
                            ManufacturerCountry = "China",
                            Price = 1989.0,
                            Quantity = 3,
                            Title = "Coffee machine 5",
                            WarrantyInMonths = 6
                        },
                        new
                        {
                            Id = new Guid("e68a5257-3154-41fb-b1ae-c7c9d4134dc0"),
                            Capacity = 12.0,
                            CatalogId = 2,
                            Description = "Good teapot",
                            ImgUrl = "https://content.rozetka.com.ua/goods/images/big_tile/45610581.jpg",
                            ManufacturerCountry = "China",
                            Price = 2359.0,
                            Quantity = 9,
                            Title = "Coffee machine 6",
                            WarrantyInMonths = 30
                        },
                        new
                        {
                            Id = new Guid("6af337c3-e1c3-4aa1-bbca-b148d72b878f"),
                            Capacity = 12.0,
                            CatalogId = 2,
                            Description = "Good teapot",
                            ImgUrl = "https://content1.rozetka.com.ua/goods/images/big_tile/160843463.jpg",
                            ManufacturerCountry = "China",
                            Price = 3599.0,
                            Quantity = 10,
                            Title = "Coffee machine 7",
                            WarrantyInMonths = 24
                        },
                        new
                        {
                            Id = new Guid("48bbdfec-ed48-4665-9568-0582a6001ea3"),
                            Capacity = 12.0,
                            CatalogId = 2,
                            Description = "Good teapot",
                            ImgUrl = "https://content.rozetka.com.ua/goods/images/big_tile/167686386.jpg",
                            ManufacturerCountry = "China",
                            Price = 4179.0,
                            Quantity = 8,
                            Title = "Coffee machine 8",
                            WarrantyInMonths = 6
                        },
                        new
                        {
                            Id = new Guid("04f6cd6b-28ba-46a4-bb05-fb6cf96bf673"),
                            Capacity = 12.0,
                            CatalogId = 2,
                            Description = "Good teapot",
                            ImgUrl = "https://content.rozetka.com.ua/goods/images/big_tile/13821301.jpg",
                            ManufacturerCountry = "China",
                            Price = 1789.0,
                            Quantity = 5,
                            Title = "Coffee machine 9",
                            WarrantyInMonths = 24
                        },
                        new
                        {
                            Id = new Guid("a561142a-d5d8-4e14-b0ac-472aacd20693"),
                            Capacity = 12.0,
                            CatalogId = 2,
                            Description = "Good teapot",
                            ImgUrl = "https://content2.rozetka.com.ua/goods/images/big_tile/11675316.jpg",
                            ManufacturerCountry = "China",
                            Price = 6789.0,
                            Quantity = 7,
                            Title = "Coffee machine 10",
                            WarrantyInMonths = 12
                        });
                });

            modelBuilder.Entity("Module6HW7.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Module6HW7.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HashPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Patronymic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Module6HW7.Models.Order", b =>
                {
                    b.HasOne("Module6HW7.Models.OrderStatus", "OrderStatus")
                        .WithMany()
                        .HasForeignKey("OrderStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderStatus");
                });

            modelBuilder.Entity("Module6HW7.Models.OrderProduct", b =>
                {
                    b.HasOne("Module6HW7.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Module6HW7.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Module6HW7.Models.Product", b =>
                {
                    b.HasOne("Module6HW7.Models.Catalog", "Catalog")
                        .WithMany()
                        .HasForeignKey("CatalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Catalog");
                });

            modelBuilder.Entity("Module6HW7.Models.User", b =>
                {
                    b.HasOne("Module6HW7.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });
#pragma warning restore 612, 618
        }
    }
}
